### PR TITLE
Widgets for the conditional fields

### PR DESCRIPTION
**Pull request by ale-rt**
They prevent client side validation to kick in when the conditions that show the fields are not met.

Refs. https://github.com/syslabcom/scrum/issues/2615

### CODE REVIEW

**Comment by ale-rt** [comment]
Requires https://github.com/euphorie/Euphorie/pull/761 for this to work

**Review by mauritsvanrees — APPROVED** [review]
This is mostly working fine.  I have merged the Euphorie PR.

I see one problem though.  The error is shown twice for rich text fields.  For example when editing a survey and enabling the custom notification:

Screenshot 2024-09-11 at 12 43 42

So the html/textarea widget seems to already show its error without needing the explicit showing of an error as this PR does.  But for the simple text line widget, it *is* needed.

I approve the PR because this is an improvement, but I won't merge yet.  You can decide if you merge and then open a new issue, or if you try to fix it first.

**Comment by ale-rt** [comment]
Sure, I will fix it :) Thanks a lot!

**Comment by mauritsvanrees** [comment]
Thanks, that works.

**Pull request merged**
