### PR TITLE
Newsletter on translations2

### PR DESCRIPTION
**Pull request by angeldasangel**
Translations for IT and LT.

### CODE REVIEW

**Comment by reinhardt** [comment]
Should the base branch for this be `newsletter-on` maybe? There are suspiciously many commits that would be added to main...

**Comment by angeldasangel** [comment]
> Should the base branch for this be newsletter-on maybe? There are suspiciously many commits that would be added to main...
yes, @reinhardt , that should be merged to the newsletter-on branch.

**Comment by angeldasangel** [comment]
I have also added some changes for language "hu" to newsletter-on-translations2.

**Comment by reinhardt** [comment]
> yes, @reinhardt , that should be merged to the newsletter-on branch.

I've switched the base branch.

**Pull request merged**
