### PR TITLE
Implement dependencies for all the widgets

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
Probably it would be better to add this to some widget wrapper element, but I tried to not diverge too much to what we have in NuPlone since ages, see e.g.:

- https://github.com/euphorie/NuPlone/blob/ade6376eb3e1d6d58c376d82fa99b1bbc59fa4c5/plonetheme/nuplone/z3cform/templates/text_input.pt#L7

**Comment by mauritsvanrees** [comment]
I am missing something.  Where is `ploneintranet_classes` defined?  I don't see that anywhere in `parts/omelette` of my oira buildout.

On the ploneintranet side I am at url http://localhost:8000/intranet/apps/assessments/@@oira-edit/eu/test-sector-maurits/maurits-oira-tool/standaard, which requests http://localhost:8000/tool-creator/sectors/eu/test-sector-maurits/maurits-oira-tool/standaard/@@quaive-edit and this gives a `LocationError`:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 391, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 98, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module z3c.form.form, line 239, in __call__
  Module z3c.form.form, line 163, in render
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 58, in __call__
  Module zope.pagetemplate.pagetemplate, line 134, in pt_render
  Module Products.PageTemplates.engine, line 365, in __call__
  Module z3c.pt.pagetemplate, line 174, in render
  Module chameleon.zpt.template, line 331, in render
  Module chameleon.template, line 193, in render
  Module 3867d0256a3f586702a6e98c32673db5, line 1024, in render
  Module a6ab602b3cf17c5288809e4bc0a93505, line 511, in render_layout
  Module 3867d0256a3f586702a6e98c32673db5, line 691, in __fill_content
  Module zope.tales.expressions, line 248, in __call__
  Module Products.PageTemplates.Expressions, line 224, in _eval
  Module Products.PageTemplates.Expressions, line 155, in render
  Module z3c.form.widget, line 154, in render
  Module zope.browserpage.viewpagetemplatefile, line 47, in __call__
  Module zope.pagetemplate.pagetemplate, line 134, in pt_render
  Module Products.PageTemplates.engine, line 365, in __call__
  Module z3c.pt.pagetemplate, line 174, in render
  Module chameleon.zpt.template, line 331, in render
  Module chameleon.template, line 217, in render
  Module chameleon.utils, line 20, in raise_with_traceback
  Module chameleon.template, line 193, in render
  Module 818afc414d2bc07104e6e4b547cfceea, line 136, in render
  Module zope.tales.expressions, line 248, in __call__
  Module Products.PageTemplates.Expressions, line 216, in _eval
  Module zope.tales.expressions, line 153, in _eval
  Module Products.PageTemplates.Expressions, line 133, in trustedBoboAwareZopeTraverse
  Module zope.traversing.adapters, line 149, in traversePathElement
   - __traceback_info__: (<plonetheme.nuplone.z3cform.directives.WidgetDependencyView object at 0x171d3e490>, 'ploneintranet_classes')
  Module zope.traversing.adapters, line 54, in traverse
   - __traceback_info__: (<plonetheme.nuplone.z3cform.directives.WidgetDependencyView object at 0x171d3e490>, 'ploneintranet_classes', [])
zope.location.interfaces.LocationError: zope.location.interfaces.LocationError: (<plonetheme.nuplone.z3cform.directives.WidgetDependencyView object at 0x171d3e490>, 'ploneintranet_classes')

 - Expression: "dependencies/ploneintranet_classes"
 - Filename:   ... /osha/oira/ploneintranet/z3cform/templates/text_input.pt
 - Location:   (line 11: col 18)
 - Source:     <label class="${dependencies/ploneintranet_classes}"
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "tile:statusmessages"
 - Filename:   ... uphorie/src/euphorie/content/browser/templates/layout.pt
 - Location:   (line 62: col 28)
 - Source:     <div id="content">
                                       ^
 - Expression: "context/@@layout/macros/layout"
 - Filename:   ... ira/src/osha/oira/ploneintranet/templates/quaive-form.pt
 - Location:   (line 7: col 23)
 - Source:     metal:use-macro="context/@@layout/macros/layout"
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  template: <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x1711b0730>
               options: {}
               args: ()
               nothing: None
               modules: <zope.pagetemplate.engine.TraversableModuleImporter object at 0x10cd643d0>
               request: <WSGIRequest, URL=http://localhost:8000/tool-creator/sectors/eu/test-sector-maurits/maurits-oira-tool/standaard/@@quaive-edit>
               view: <TextWidget 'form.widgets.title'>
               context: <Survey at /Plone/sectors/eu/test-sector-maurits/maurits-oira-tool/standaard>
               views: <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x171d3e070>
               default: <DEFAULT>
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x17339bf80>
               loop: {}
               target_language: None
               translate: <function BaseTemplate.render.<locals>.translate at 0x173b6f670>
               attrs: {'class': '${dependencies/ploneintranet_classes}', 'title': '${view/field/description}', 'data-pat-depends': '${dependencies/data_pat_depends}'}
               dependencies: <plonetheme.nuplone.z3cform.directives.WidgetDependencyView object at 0x171d3e490>
```

**Comment by ale-rt** [comment]
That is a NuPlone thing https://github.com/euphorie/NuPlone/blob/ade6376eb3e1d6d58c376d82fa99b1bbc59fa4c5/plonetheme/nuplone/z3cform/directives.py#L80-L119

You probably need to checkout/update it:
```
[sources]
NuPlone = git git@github.com:euphorie/NuPlone.git branch=master
```

**Review by mauritsvanrees — APPROVED** [review]
Ah, NuPlone explains it.  Now it works.

One suggestion to fix a typo, but this was already there, so I approve the PR.

**Pull request merged**
