### PR TITLE
Dashboard banner

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Review by reinhardt — CHANGES_REQUESTED** [review]
Why don't you add a boolean column called `call-for-action-banner-disabled`? Saving a string in a generic text column obscures the table schema and makes it harder to write SQL.

**Comment by reinhardt** [comment]
See also https://github.com/euphorie/osha.oira/pull/164#issuecomment-1321938976

**Comment by ale-rt** [comment]
> Why don't you add a boolean column called `call-for-action-banner-disabled`? Saving a string in a generic text column obscures the table schema and makes it harder to write SQL.

No thanks... I want this to be flexible

**Review by thet — APPROVED** [review]
LGTM

**Pull request merged**
