### PR TITLE
Update statistics: Fixed adding on empty database

### PR DESCRIPTION
**Pull request by reinhardt**

### CODE REVIEW

**Review by thet — APPROVED** [review]
LGTM

**Comment by reinhardt** [comment]
Just what it says on the tin. Adding statistics when the database is still empty did not work. This PR is supposed to fix that.

(I think there were test failures though. And not a high priority because we rarely have an empty statistics DB, except on a fresh instance or when we wipe it for some reason.)

**Comment by ale-rt** [comment]
Thanks, do you plan to work to have this merged or should we close this one?

**Comment by reinhardt** [comment]
I currently have no plans. As I said, low priority. Come to think of it, this may have become obsolete with https://github.com/syslabcom/scrum/issues/2348. So, let's close it.

**Pull request closed without merging**
