### PR TITLE
Fix IOSHAContentSkinLayer registration

### PR DESCRIPTION
**Pull request by reinhardt**
Ref syslabcom/scrum#1979

### CODE REVIEW

**Comment by ale-rt** [comment]
This is mysterious, but I think the biggest issue is that the IOSHAContentSkinLayer overrides the NuPlone and not the Euphorie one.

See:

- https://github.com/euphorie/osha.oira/blob/e46e5d91f41e9e4a109415c500a17f72da44f573/src/osha/oira/interfaces.py#L11

Can you test if my suspect is right?

**Comment by reinhardt** [comment]
How would you test that? What issue do you expect?

**Comment by ale-rt** [comment]
> How would you test that? 

I would revert the change you are proposing and add the modification I am proposing.

> What issue do you expect?

The answer to your question is "None".
If you were instead asking: "What issue do we have right now?" the answer is: "We do not have the proper skin layer inheritance".

The package `osha.oira` depends on `euphorie` that depends on `plonetheme.nuplone`.

The layers should respect that hierarchy in order for the customizations to work properly.

**Comment by reinhardt** [comment]
> I would revert the change you are proposing and add the modification I am proposing.

And then what? Just making that change will not do anything. I will at least have to start up the instance, and probably call some view or whatever.

> If you were instead asking: "What issue do we have right now?" the answer is: "We do not have the proper skin layer inheritance".

OK and how does that manifest? That sounds very theoretical. I need some issue that I can reproduce so that I can verify that it is fixed by the change you're proposing.

**Comment by reinhardt** [comment]
Wait a minute, are you still talking about the issue that the IOSHAContentSkinLayer is not active? When you wrote “This is mysterious, but I think the biggest issue is ...” I thought you were referring to a new issue, but maybe I misunderstood that?

**Comment by reinhardt** [comment]
I've changed the inheritance for good measure in [e7333cf](https://github.com/euphorie/osha.oira/commit/e7333cf17d714a8ddb215e98fb87c646c1eb64b1), but as soon as I restore that interface declaration in the zcml the quaive-edit view returns 404 again.

**Comment by ale-rt** [comment]
> > I would revert the change you are proposing and add the modification I am proposing.
> 
> And then what? Just making that change will not do anything. I will at least have to start up the instance, and probably call some view or whatever.
> 
> > If you were instead asking: "What issue do we have right now?" the answer is: "We do not have the proper skin layer inheritance".
> 
> OK and how does that manifest? That sounds very theoretical. I need some issue that I can reproduce so that I can verify that it is fixed by the change you're proposing.

I think you figure it out all by yourself by now.
If not please let's make a call.

**Comment by ale-rt** [comment]
Question: did you install first osha.oira and then Euphorie?

**Comment by reinhardt** [comment]
I think so. I assumed that euphorie would be installed as a dependency of osha.oira, but IIRC it wasn't and I installed euphorie manually afterwards. Do you think that caused the issue? How?

**Comment by ale-rt** [comment]
> I think so. I assumed that euphorie would be installed as a dependency of osha.oira, but IIRC it wasn't and I installed euphorie manually afterwards.

This caught me off guard as well. 

See: https://github.com/euphorie/osha.oira/pull/247/files#diff-337d185a6f002c5bacab1003a4f8acd7e506ed6e15b3f9ff50fde4743e21dd41R7

Can you review #246 and #247 please?

> Do you think that caused the issue?

Yes, and I can confirm by installing the packages in the proper order.

> How?

Because the layers are layered :D

If you have `package.foo` that install `IFooBrowseLayer` and then `package.bar` that installs `IBarBrowserLayer`, the layer that will take the precedence is the last one you install.

Does this explanation seems reasonable to you?
Should we close this PR in and use the approach suggested in #247?

**Comment by reinhardt** [comment]
Ah, I didn't know there was an order of precedence. That would explain some things. But if we make IOSHAContentSkinLayer inherit from IEuphorieContentLayer then the more specific layer (IOSHAContentSkinLayer) will take precedence, regardless of the install order, right?

#247 claims to be only about tests, but I saw now that it also changes the profile dependencies and interface inheritance. That's a bit sneaky, but OK, I noticed. I'll double check whether this fixes the issue for me as well, and if so, I'm fine with that!

**Comment by ale-rt** [comment]
I think this is already sorted out in another way and anyway the PR is not in a mergeable state.
Feel free to reopen.

**Pull request closed without merging**
