### PR TITLE
quaive-unpublish: only for surveygroup, only small template needed.

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Review by ale-rt — COMMENTED** [review]
I think you could have done this form in quaive, see 
- 
https://github.com/quaive/quaive.osha/blob/4745d0edcd020cfde87c12b8e17f2e06bf09aca4/src/quaive/osha/browser/templates/assessments-remote-delete.pt
- https://github.com/quaive/quaive.osha/blob/4745d0edcd020cfde87c12b8e17f2e06bf09aca4/src/quaive/osha/browser/assessments.py#L724-L767

**Comment by mauritsvanrees** [comment]
> I think you could have done this form in quaive

I was going to say "not really", because for the handling of a POST request we do have to call the [unpublish view in euphorie](https://github.com/euphorie/Euphorie/blob/7e4dfb8cb4b298e61106df3847b0a559575841e4/src/euphorie/content/browser/surveygroup.py#L261-L274).

But yes, we could let Quaive just POST to `@@publish` instead of `@@quaive-publish`.

Then we are left with the few lines we have in the template in this PR:

```
  <span tal:replace="structure context/@@authenticator/authenticator"></span>
  <p i18n:translate="unpublish_confirm">Are you sure you want to unpublish this OiRA Tool?</p>
```

I can easily move the label to the Quaive side of course.
But the authenticator still needs to be generated on the OiRA side.  I did not have the authenticator at first, but then got a plone.protect error.

We can get `@@authenticator/token` from OiRA.  Then we can get rid of this extra quaive-unpublish view
Let me try.

(For `@@quaive-publish` the situation is similar, but there we really need the small template on the OiRA side so Oira can decide which one or more out of four different info/warning messages to display, depending on the status of the survey.)

**Comment by mauritsvanrees** [comment]
I have removed the quaive-unpublish view.

**Comment by mauritsvanrees** [comment]
Oops, forgot to (force) push my changes.

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
